### ISSUE TITLE
TC CLI always returns "Folder not found"

### ISSUE THREAD

**Issue by iAmcDiddy** [thunderclient/thunder-client-support#1560]
### Discussed in https://github.com/thunderclient/thunder-client-support/discussions/1559

<div type='discussions-op-text'>

<sup>Originally posted by **iAmcDiddy** June 13, 2024</sup>

## Update
I tried this in another project that was NOT upgraded to the new schema and it worked.

I have updated to the latest version and am trying to run all requests in a folder.
When I run the --debug command it says 'saveToWorkspace' is undefined (although it's checked in my settings) and also 'customLocation' is undefined.
My project has a 'thunder-tests' folder and all collections defined under that.  There is a collection named "Execute_SQL_Query" and a folder in that collection named "Unauthorized".  I used the 'tab' to complete the folder names while building the command.
Below is my command prompt, command and result.  Any help is greatly appreciated.
![image](https://github.com/thunderclient/thunder-client-support/assets/6363477/95994861-3a11-4350-8ae8-62ced8c54e3e)

I have also tried not specifying the thunder-tests folder but got the same error:
![image](https://github.com/thunderclient/thunder-client-support/assets/6363477/59415998-c3f8-4674-bab4-3fa53e1d5e2c)
</div>

**Comment by rangav** [comment]
Hi @iAmcDiddy the commands should be run from root of the project folder 

1. type `cd ..` and run the `tc --fol` command again.

**Comment by iAmcDiddy** [comment]
I can't believe that's the fix, I thought I tried everything.  So running an individual folder works for me now.  I have data files for each folder and using this command picks up the .csv that is associated with that folder (I don't need to use --data-file):
`tc --fol "DataDriven-PositiveSpend"`
BUT when I try to run the parent collection, it only runs the Request in each Folder once.  I would force the 'iterations' in the collection to a number, but each data file has a different number of data points in it (some have 1, some have 4).
Any suggestions on how to get ALL the data to be utilized while running the whole collection?
Many thanks!

This question is related to a closed issue: [1529](https://github.com/thunderclient/thunder-client-support/issues/1529)

**Comment by iAmcDiddy** [comment]
Each folder has their own data file and 'iterations' set correctly.
I can run these commands:
`tc --fol "DataDriven-PositiveAssessment" --report html`
`tc --fol "DataDriven-NegativeAssessment" --report html`
but this doesn't work:
`tc --fol "DataDriven-PositiveAssessment,DataDriven-NegativeAssessment" --report html`

Shouldn't I be able to run multiple folders?

**Comment by rangav** [comment]
Multiple folders not supported

Docs
https://docs.thunderclient.com/cli/run-collection

**Comment by iAmcDiddy** [comment]
What am I missing?  I can't run my (data driven) collection as a collection and I can't run it as folders either.
Can you provide a suggestion?  Do I need to resort to running 20 folder-level sets each time?  That will use up my 500 collections/month for just this project.

**Comment by rangav** [comment]
@iAmcDiddy 

can you please verify your subscription by using below form
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
Did not understand your question? Please provide more details 

The documentation has all the details 
https://docs.thunderclient.com/cli/run-collection


> What am I missing? I can't run my (data driven) collection as a collection and I can't run it as folders either. Can you provide a suggestion? Do I need to resort to running 20 folder-level sets each time? That will use up my 500 collections/month for just this project.

**Comment by iAmcDiddy** [comment]
I have this setup:
### Collection 1
#### Folder 1
...
#### Folder 12
### Collection 2
#### Folder 1
...
#### Folder 12
Each folder has a Request and a data file with multiple (~4) sets of data.
Running a Collection won't work even if I pad each data file with the same number of rows and set that number as the iteration on the Collection.
Running each Folder will work, but since there are so many - I will only be able to run the full set maybe once per week because of the limitation on number of collections executed per month.
Is there a better solution than running these at the folder level? Can we get an extension on the number of collections/month until support for running at the collection level as we would like, is supported?

**Comment by rangav** [comment]
Multiple data files not supported, only single main data file is supported 

alternatively you can skip folders and run selected folders

**Comment by cw1934** [comment]
@rangav I feel like I'm missing something as to what's preventing this from working.  Running Multiple _Collections_ via CLI is supported, and running Multiple _Requests_ is also supported.  If multiples of layers both above and below Folders are supported, what is preventing the capability from being added to run Multiple _Folders_ via CLI?  It seems like a gap given other supported functionality, and seems like a valid use case given the described folder-specific aspects that come into play with this use case.

**Comment by rangav** [comment]
We will add this feature to roadmap and implement asap

**Comment by rangav** [comment]
The feature is implemented in CLI v1.16.0

- `tc --fol 'folNameOrId1,folNameOrId2'`

**Comment by iAmcDiddy** [comment]
The folders are being executed when using the above syntax, it even puts all the results into 1 report.  However, each of our folders have data files defined and running them this way does NOT utilize the data from those files.  So I would not consider this issue closed/completed.

**Comment by rangav** [comment]
Ok got

**Comment by CharlieSnowCode** [comment]
Yes, we would like them to utilize the associated data file at the folder level.  Ideally they would generate just 1 report (like it does now).  Many thanks for looking into this!

**Comment by iAmcDiddy** [comment]
Yes, we would like them to utilize the data file associated at the folder level. Ideally they would generate just 1 report (like it does now). Many thanks for looking into this!

**Comment by rangav** [comment]
I have published the new version v1.16.1 to run multiple folders. Currently, it will only generate only individual separate reports.

Please test and let me know your feedback.

**Comment by iAmcDiddy** [comment]
I've been on vacation, I will look into this ASAP.  Thank you.

**Comment by iAmcDiddy** [comment]
This feature appears to be working.  I have one command like
`tc --fol 'F1,F2,F3,F4,F5,F6' --end 'Dev'`
which executes the requests in each folder using the data file specified at the folder level.
I am noticing 2 low-level bugs that we're working around.

1. When you change the number of rows in a data file and change the value of 'Iterations' in the Run Collection UI and save it - the new value isn't saved.  We have to manually open and edit the _info.json file
2. There is a table that shows a 'Summary Report' for each folder while executing, then one at the end that shows 1 Total Iteration (which I guess is true) and also Total Requests value of 1, which is incorrect.

Thank you very much for implementing this, we will use it as is and look forward to upcoming improvements.

**Comment by rangav** [comment]
Hi @iAmcDiddy 

I am following up to see if you still have problem with issue -1 above?

**Comment by 3rdTimeCharm** [comment]
This is the author (remember I deleted the "iAm" account).  Yes, that issue #1 still exists.  I just tried running a folder with a new data file and the _info.json file did not get the changes.  In fact I changed all the values (Run Type, Concurrent, Iterations and Data) and none of those values made it into that _info file.

**Comment by rangav** [comment]
That's by design. The CLI does not update the `_info.json` file—only the extension modifies the JSON files. 

The CLI is for read-only data processing, and you can pass additional information using arguments.

**Comment by 3rdTimeCharm** [comment]
Oh, sorry I wasn't clear about that.  I'm using the UI to run the folder in this case and on occasion it does update that file.  But typically it does not.

**Comment by rangav** [comment]
Okay, thank you for the clarification. I will look into it.

**Comment by rangav** [comment]
I just now testing `_info.json` is updating for me correctly.

@iAmcDiddy or @3rdTimeCharm 

Can we schedule a call to look into the issue?, Please use the below form to share your availability
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
feel free to continue the discussion if you still have issues.
